-- stg_diagnoses.sql
-- Unifies diagnosis codes from both sources. DE-SynPUF ships ICD-9-CM
-- (it predates the ICD-10 transition); Synthea Condition resources use
-- SNOMED CT codes in the sample data generated by the standard Synthea
-- modules. Both are kept as-is with a coding_system flag rather than
-- cross-walked - see ADR-004 in docs/decisions/ADRs.md for why this repo
-- does not attempt a SNOMED-to-ICD crosswalk (out of scope for a
-- portfolio-scale project; a real implementation would need one).

with synpuf_diagnoses as (

    select distinct
        diagnosis_bk,
        'icd9' as coding_system,
        record_source,
        load_dts
    from {{ source('bronze', 'synpuf_inpatient_claim_diagnoses') }}

),

synthea_diagnoses as (

    select distinct
        diagnosis_bk,
        'snomed' as coding_system,
        record_source,
        load_dts
    from {{ source('bronze', 'synthea_conditions') }}
    where diagnosis_bk is not null

),

unioned as (

    select * from synpuf_diagnoses
    union all
    select * from synthea_diagnoses

)

select * from unioned
